<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphsTraverser" nsURI="http://GraphTraverser/PL" nsPrefix="graphTraverser">
  <eAnnotations source="transformation">
    <details key="technology" value="EOL"/>
    <details key="name" value="VertexNumbering.eol"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="gpl" value="../structure/GraphsConcept.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="../structure/GraphsConcept.ecore#//Graph">
    <eOperations name="calculateFollowers">
      <eParameters name="idx" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="../structure/GraphsConcept.ecore#//Node">
    <eOperations name="setId">
      <eParameters name="ident" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
